/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.panosmatsinopoulos.composingsuspendingfunctions

import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlin.system.measureTimeMillis

suspend fun doSomethingUsefulOne(): Int {
    delay(1_000L)
    return 13
}

suspend fun doSomethingUsefulTwo(): Int {
    delay(1_000L)
    return 29
}

suspend fun concurrentSum() = coroutineScope {
    val one = async { doSomethingUsefulOne() }
    val two = async { doSomethingUsefulTwo() }
    one.await() + two.await()
}

fun main() {
    println("Main starting...")
    val time = measureTimeMillis {
        runBlocking {
            println(concurrentSum())
        }
    }

    println("Took $time ms")
    println("Main ending!")
}
